plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {

    api 'com.squareup.okhttp3:okhttp:4.12.0'

    api 'com.google.code.gson:gson:2.10.1'

    api 'org.jsoup:jsoup:1.17.2'

    api 'org.mozilla:rhino:1.7.14'

    api 'org.jetbrains:annotations:24.1.0'

}
